services:
  reverse-proxy:
    image: traefik:v3.2
    restart: unless-stopped
    container_name: traefik
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--providers.docker=true"
      - "--log.level=INFO"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=reg.doroshenko@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"

      # Static files:
      - "--providers.file.directory=/var/lib/try-canada/static"
      - "--providers.file.watch=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/try-canada/letsencrypt:/letsencrypt
      - /etc/ssl/private/try-canada-ssl.key:/certs/try-canada-ssl.key
      - /etc/ssl/certs/try-canada-ssl.cer:/certs/try-canada-ssl.cer
      - ~/reverse-proxy:/config
      - /var/log/traefik/:/var/log/traefik/

    labels:
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.try-canada.org`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
    networks:
      - traefik-net

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - /var/lib/try-canada/static:/usr/share/nginx/html:ro
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.nginx.rule=Host(`try-canada.org`) && PathPrefix(`/static/`)"
  #     - "traefik.http.routers.nginx.entrypoints=websecure"
  #     - "traefik.http.routers.nginx.tls=true"
  #     - "traefik.http.routers.nginx.tls.certresolver=myresolver"
  #   networks:
  #     - traefik-net

networks:
  traefik-net:
    name: traefik-net
